import os
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
AI_DB_PATH = ROOT_DIR / "db" / "ai_quality.db"
MAIN_DB_PATH = ROOT_DIR / "alphadog.db"
MODEL_DIR = ROOT_DIR / "models" / "entry_quality"

SERVICE_HOST = "0.0.0.0"
SERVICE_PORT = 8010
MODEL_KEYS = ("alpha", "normal")
MIN_TRAINING_SAMPLES = 1000
MIN_VALIDATION_SAMPLES = 300
VALIDATION_FRACTION = 0.20
MODEL_MAX_AGE_HOURS = 48
MODEL_LAST_KNOWN_GOOD_HOURS = 24 * 7
ALLOW_THRESHOLD = 62.0
PROBE_THRESHOLD = 55.0
PROBE_MARGIN_PCT = 0.05
AI_EXECUTION_MODE = os.getenv("AI_EXECUTION_MODE", "shadow").strip().lower()
MIN_USABLE_FEATURES = 8
MIN_FEATURE_COVERAGE = 0.35
ESTIMATED_COST_R = 0.03
MAX_LIVE_POSITION_FACTOR = float(os.getenv("AI_MAX_POSITION_FACTOR", "1.0"))
SAMPLE_RETENTION_DAYS = 180
DECISION_RETENTION_DAYS = 180
